---
title: "Explanation about my topic"
description: |
  A short description of the post.
author:
  - name: Deschuyteneer Audry
    url: {}
date: 04-18-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I am choosing the topic “What is the influence of obesity on the body?”. Because someone in my family died of obesity. She was eating too much, and it was lethal to her. Obesity is a problem that affects many people around the world. I think it is important to offer solutions to allow all these people to lose weight and have a better lifestyle. There are already awareness campaigns to show the dangers of overweight, but I think we can do better to educate as many people as possible. People do not always realize the dangers of being overweight, and usually they do not pay attention until they have a serious health problem. Second, people who are overweight quickly feel assaulted when someone tries to talk to them about it, which does not help solve the problem. But the main problem is the society which pushes people to consume more and more. So, we should help people to limit their consumption in order to reduce the problems associated with too much consumption. My goal is to show what are the problems associated with being overweight and what is the origin of these problems. Are people alone responsible for their weight or are there other factors that influence weight gain?


After analysing the different articles, I learned that obesity can be responsible for a lot of problems. Even problems we would not have thought of. Obesity lowers our immune defense. People who are overweight or obese are more likely to get sick than people who are not overweight. I have also learned that obesity can stem from a genetic problem and therefore people who are overweight are not always responsible for this.

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

